opencrvs/opencrvs-countryconfig

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
.github/workflows/publish-release.yml
.github/workflows/publish-to-dockerhub.yml
.github/workflows/test.yml

Fix warnings on pipelines caused by outdated actions:

Update Docker and checkout actions to get rid of warnings

---

src/form/index.ts
src/utils/users.ts

https://github.com/opencrvs/opencrvs-core/pull/6925
Dependent on this PR

fix: simplify hierarchy now that it can be queried through graphql

---

infrastructure/docker-compose.deploy.yml

This PR adds commits to `release-v1.5.0` from task 7016 which are not already cherry-picked

Cherry pick 7016

---

src/translations/client.csv

fix overlap in location picker

---

src/api/dashboards/queries.ts

chore(ocrvs-7138): update dashboard query with the recent correction flow changes

---

src/api/notification/sms-service.ts

https://github.com/opencrvs/opencrvs-core/issues/7178
This parsing wasn't changed to use CSV's. This caused the SMS messages to crash when sending them. Updated the compileMessages to read the CSV file.

fix: sms not being sent

---

src/form/birth/optional-fields.ts
src/form/common/common-optional-fields.ts
src/form/death/custom-fields.ts
src/form/types/types.ts

Also remove inputFieldWidth prop

chore: update weight at birth postfix

---

infrastructure/environments/setup-environment.ts

Passwords with special characters stop Kibana from starting up:

Remove special characters from the password generation

---

src/api/certificates/source/Farajaland-birth-certificate-v2.svg
src/form/birth/index.ts
src/form/common/default-validation-conditionals.ts
src/form/death/index.ts

Core PR: https://github.com/opencrvs/opencrvs-core/pull/7879
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/1149
Countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/309

chore: clean up existing mosip code

---

src/api/certificates/source/Farajaland-birth-certificate-v2.svg

@Siyasanga I applied your fix here: https://github.com/opencrvs/opencrvs-farajaland/pull/1166

fix: error in the farajaland birth certificate svg

---

src/translations/client.csv

[#7909 - core](https://github.com/opencrvs/opencrvs-core/issues/7909)
Removed the translations relevant to nationalID integration [[#7938].](https://github.com/opencrvs/opencrvs-core/pull/7938)

chore: cleaned up the national ID integration code

---

package.json
src/form/tennis-club-membership.ts
yarn.lock

- Update events package
- Add emptyValueMessages for eventConfig

feat: add value missing definitions for summary

---

CHANGELOG.md
src/translations/client.csv

This is to allow country implementation to have custom Full name ordering
e.g start with LastName or FirstName
https://github.com/opencrvs/opencrvs-core/issues/6830

Add humanName constant to the copy

---

infrastructure/backups/backup.sh
infrastructure/backups/download.sh
infrastructure/backups/restore.sh
infrastructure/clear-all-data.sh
infrastructure/deployment/deploy.sh
infrastructure/docker-compose.deploy.yml
infrastructure/server-setup/tasks/data-partition.yml

- Removed the reset metabase function and its peripheral completely
- Removed all the metabase volumes
- Removed all backup metabase volumes
- From ansible playbook making them absent

Ocrvs 8043 for v.1.7.0

---

package.json
src/form/tennis-club-membership.ts
src/form/v2/birth/__snapshots__/birth.test.ts.snap
src/form/v2/birth/birth.test.ts
src/form/v2/birth/index.ts
yarn.lock

Primary PR: https://github.com/opencrvs/opencrvs-core/pull/8644
* Add required user scopes to tennis-club-membership-application and birth form conditionals
* Remove unused custom action
* Fix failing test, update snapshot

add required scopes to tennis-club and birth form conditionals

---

.github/workflows/auto-pr-to-release.yml
.github/workflows/check-changelog.yml
.github/workflows/clear-environment.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
.github/workflows/get-secret-from-environment.yml
.github/workflows/provision.yml
.github/workflows/publish-release.yml
.github/workflows/publish-to-dockerhub.yml
.github/workflows/reset-2fa.yml
.github/workflows/seed-data.yml
.github/workflows/test.yml
CHANGELOG.md
src/form/v2/birth/__snapshots__/birth.test.ts.snap
src/form/v2/birth/birth.test.ts

Goal of this PR is to upgrade and keep ubuntu version consistent in the future (next year+).
This PR is follow up to https://github.com/opencrvs/opencrvs-core/issues/6519 and implements changes from https://github.com/opencrvs/opencrvs-core/issues/7045
Breaking changes:
- Node 18 -> 20

chore: Upgrade runners to Ubuntu 24.04 as latest LTS release (#7045)

---

src/form/tennis-club-membership.ts
src/form/v2/birth/forms/declare.ts
src/translations/client.csv

issue: https://github.com/opencrvs/opencrvs-core/issues/8458
core pr: https://github.com/opencrvs/opencrvs-core/pull/8625

Form field added in declare action review page

---

src/form/v2/birth/__snapshots__/birth.test.ts.snap
src/form/v2/birth/forms/pages/father.ts

- Add dividers removed previously
- Fix issue where address details were shown wrong when mother had no details

fix: change father address conditional dependencies

---

src/form/tennis-club-membership.ts
src/translations/client.csv

Use the correct placeholder syntax to show record details in workqueues and event summary
Core PR: https://github.com/opencrvs/opencrvs-core/pull/8685

Events v2: Fix placeholder syntax in record details

---

package.json
src/form/tennis-club-membership.ts
src/form/v2/birth/forms/pages/child.ts
src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts
yarn.lock

Main PR: https://github.com/opencrvs/opencrvs-core/pull/8702
* Bump toolkit version, it now contains defaultValue and FieldType.NUMBER functionalities
* switch from `initialValue` -> `defaultValue`
* add `defaultValue: 'FAR'` for birth form country selections
* use new `FieldType.NUMBER` in `child.weightAtBirth`, also set min value to 0 there

use default values for countries, switch to FieldType.NUMBER

---

src/data-seeding/employees/source/prod-employees.csv

See related documentation change at
https://github.com/opencrvs/documentation/pull/9
Also relevant migration code at: https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/src/upgrade-to-1_7.ts#L246

Drop systemRole from prdo-employees.csv

---

src/form/tennis-club-membership.ts

https://github.com/opencrvs/opencrvs-core/issues/8741
https://github.com/opencrvs/opencrvs-core/pull/8771

v2-events print and issue scope fixed in tennis club print action

---

src/form/v2/birth/index.ts
yarn.lock

[#8725](https://github.com/opencrvs/opencrvs-core/issues/8725)
core: https://github.com/opencrvs/opencrvs-core/pull/8827

CREATE action removed from config

---

.github/workflows/on-pull-request.yaml

How new flow looks?  https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/13656108499

fix: Sync between Countryconfig and Farajaland: Separate steps to jobs

---

src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts
src/translations/client.csv

Related PR: https://github.com/opencrvs/opencrvs-core/pull/8847
Birth form checkboxes should not be required.

Remove required from checkboxes in birth form

---

src/translations/client.csv

- Add rows for date config
- Update key for time config
https://github.com/opencrvs/opencrvs-core/pull/8856

fix: add configurable date format

---

src/form/v2/birth/forms/pages/documents.ts
src/translations/client.csv

Birth registration number -> Birth certificate
None -> Other

Fix uploadable document types

---

src/translations/client.csv

Core PR: https://github.com/opencrvs/opencrvs-core/pull/8947

add v2.buttons.changeAll translation

---

build-and-push.sh

See comment here: https://github.com/opencrvs/opencrvs-farajaland/pull/1292#discussion_r2009741051

fix: Avoid usage of bash string-magic

---

src/translations/client.csv

add corresponding translations
https://github.com/opencrvs/opencrvs-core/pull/9084

chore: add translations

---

src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts
src/translations/client.csv

https://github.com/opencrvs/opencrvs-core/issues/9142

fix age and address labels for informant, mother and father

---

src/form/v2/birth/forms/pages/child.ts
src/form/v2/birth/forms/pages/mother.ts

https://github.com/opencrvs/opencrvs-core/issues/8893
- Change childs weight at birth min to 0
- Change mothers previous births input type to number, and add min to 0

fix configuration for weight at birth and previous births

---

package.json
src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/mother.ts
yarn.lock

https://github.com/opencrvs/opencrvs-core/issues/9159
https://github.com/opencrvs/opencrvs-core/pull/9170

add new 'ConditionalType.DISPLAY_ON_REVIEW' for dob unknown and same as mothers place of birth fields

---

src/form/v2/birth/forms/pages/father.ts

move `ConditionalType.DISPLAY_ON_REVIEW` from dob -> to dobUnknown field

move conditional to correct field

---

.github/PULL_REQUEST_TEMPLATE.md

Just like opencrvs-core
pr template added in country-config

pull request description template added

---

infrastructure/clear-all-data.sh
infrastructure/docker-compose.deploy.yml

Link to the GitHub issue (or name the branch `ocrvs-<issue #>`)

ocrvs-6998(Image updated for minio-mc)

---

src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts

https://github.com/opencrvs/opencrvs-core/issues/9174
Fix incorrect validator in informant.dob

fix informant.dob validator

---

src/form/v2/birth/forms/pages/father.ts

https://github.com/opencrvs/opencrvs-core/issues/9172

Fix conditional configuration for father address fields

---

src/form/v2/birth/forms/pages/informant.ts

No GitHub issue, this was found when porting V1 tests to V2.

add default nationality and address for informant

---

src/form/tennis-club-membership.ts
src/form/v2/birth/index.ts
src/translations/client.csv

- Allow registrar to access validate flow
- Update register flow modal title

Ocrvs 9074 b

---

src/form/v2/birth/forms/print-certificate.ts

No issue. Found when porting tests.

add national id and brn as collector id types, add informant.relation to collector verify page

---

src/form/v2/birth/forms/pages/informant.ts

https://github.com/opencrvs/opencrvs-core/issues/9203

fix phone number not allowing empty string

---

src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts

Fix validation error message for unique nid
https://github.com/opencrvs/opencrvs-core/issues/8905#issuecomment-2804908277

Fix validation error message for unique nid

---

CHANGELOG.md
src/form/types/types.ts

Core PR: https://github.com/opencrvs/opencrvs-core/pull/9282

Added AM/PM time field type

---

src/form/types/types.ts

Update form types with recently introduced fields' types

chore: update form types

---

package.json
src/form/v2/birth/forms/print-certificate.ts
src/translations/client.csv

Link to the GitHub issue https://github.com/opencrvs/opencrvs-core/issues/9195
core pr: https://github.com/opencrvs/opencrvs-core/pull/9296
| Service                                                     | Fee |
|-------------------------------------------------------------|-----|
| Birth registration before 30 days of date of birth          | 5   |
| Birth registration between 30 days and 365 days of date of birth | 7   |
| Birth registration after 365 days of date of birth          | 15  |

Configure services for Payment view

---

package.json

Issue link : [#9239](https://github.com/opencrvs/opencrvs-core/issues/9239)
Alias `yarn environment:init`  to `yarn environment:upgrade` for clarity sake

OCRVS-9239

---

src/form/v2/birth/forms/printForm/collector-identity-verify.ts

issue: https://github.com/opencrvs/opencrvs-core/issues/8441#issuecomment-2812045477

bugfix: remove informant verification from verification page

---

infrastructure/backups/download.sh
infrastructure/backups/restore.sh
infrastructure/clear-all-data.sh
infrastructure/deployment/deploy.sh
infrastructure/server-setup/tasks/data-partition.yml

Removed metabase related stuffs in release-v1.7.0 branch

Removing metabase

---

src/form/v2/birth/forms/printForm/collector-identity-verify.ts

Link to the GitHub issue: https://github.com/opencrvs/opencrvs-core/issues/8441#issuecomment-2824230271

collector verification flow fixed

---

src/form/v2/birth/forms/printForm/collectors.ts

Link to the GitHub issue (or name the branch `ocrvs-<issue #>`)

collect condition for no parent exist

---

.github/workflows/test.yml
CHANGELOG.md

See related PR https://github.com/opencrvs/opencrvs-countryconfig/pull/654

Fix node cache

---

.github/workflows/test.yml
CHANGELOG.md

Pull changes from v1.6.4 into v1.7.2

Pull changes from v1.6.4 into v1.7.2

---

package.json
src/form/v2/birth/forms/pages/documents.ts
src/form/v2/birth/forms/printForm/collector-other.ts
yarn.lock

Github issue: https://github.com/opencrvs/opencrvs-core/issues/9211
Core PR: https://github.com/opencrvs/opencrvs-core/pull/9328

configure file names for birth form signed affidavit and proof of birth

---

package.json
src/form/v2/birth/index.ts
yarn.lock

Issue: https://github.com/opencrvs/opencrvs-core/issues/9044#issuecomment-2808408860
Countryconfig PR: https://github.com/opencrvs/opencrvs-core/pull/9317
Use field id references on summary page fields

use field references in summary

---

src/api/certificates/source/v2.birth-certificate-certified-copy.svg
src/api/certificates/source/v2.birth-certificate.svg
src/translations/client.csv

Link to the GitHub issue (or name the branch `ocrvs-<issue #>`)

v1 certified birth certificate ported to v2

---

CHANGELOG.md
infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.staging-deploy.yml
infrastructure/server-setup/tasks/users.yml

Merge 1.6.4 changes into 1.7.1

fix (v.1.7.2): Add HEARTH_MONGO_URL to docker compose files.

---

infrastructure/deployment/deploy.sh
infrastructure/docker-compose.deploy.yml
infrastructure/rotate-secrets.sh

Related issue: https://github.com/opencrvs/opencrvs-core/issues/7654
Test results are at: https://github.com/opencrvs/opencrvs-core/pull/9338

feat: Add redis ACL based password support

---

src/form/tennis-club-membership.ts
src/form/v2/birth/forms/printForm/collector-other.ts

Fixes bugs 1, 2, and 4 on https://github.com/opencrvs/opencrvs-core/issues/9336
Bug 3 will be included in a separate core PR
Core PR:

Fix print certificate flow request to someone else configurations and labels

---

.github/workflows/init-release.yml

Issue link : [#9396](https://github.com/opencrvs/opencrvs-core/issues/9396)

ocrvs-9396(New workflow added for initiate a draft release)

---

src/form/tennis-club-membership.ts
src/form/v2/birth/advancedSearch.ts

Redirect user from advanced search to advanced search result page
[#8933](https://github.com/opencrvs/opencrvs-core/issues/8933)

few more fields added in search field

---

package.json
src/form/v2/birth/forms/pages/informant.ts
yarn.lock

Core: https://github.com/opencrvs/opencrvs-core/pull/9429
Take 'parent' property into use from toolkit

feat: use parent field

---

.github/TEMPLATES/RELEASE_PR_TEMPLATE.md

Added a new release PR template

---

package.json
src/form/tennis-club-membership.ts
src/form/v2/birth/index.ts
src/translations/client.csv
yarn.lock

Ocrvs 9241

---

package.json
src/form/tennis-club-membership.ts
src/form/v2/birth/index.ts
yarn.lock

Core PR: https://github.com/opencrvs/opencrvs-core/pull/9489

configure fallback titles

---

CHANGELOG.md
infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.staging-deploy.yml

[OpenCRVS Country Configuration Template - v1.6.4](https://github.com/opencrvs/opencrvs-countryconfig/releases/tag/v1.6.4)
This release is a reference country config implementation compatible with OpenCRVS version 1.6.4.

Release v1.6.4

---

package.json
src/form/v2/birth/advancedSearch.ts
yarn.lock

Update toolkit and single import to ensure farajaland sync works

chore: update type and toolkit

---

src/form/v2/birth/forms/printForm/collector-identity-verify.ts
src/form/v2/birth/forms/printForm/collector-other.ts
src/form/v2/birth/forms/printForm/collectors.ts
src/form/v2/birth/forms/printForm/index.ts

Resolves comment: https://github.com/opencrvs/opencrvs-core/issues/9340#issuecomment-2865994962

Fix config

---

package.json
src/form/v2/birth/advancedSearch.ts
yarn.lock

Reverts opencrvs/opencrvs-countryconfig#731

Revert "Ocrvs 8426"

---

package.json
src/api/workqueue/workqueueConfig.ts
yarn.lock

Link to the GitHub issue: https://github.com/opencrvs/opencrvs-core/issues/9129

Configure 3rd column of workqueue

---

src/translations/client.csv

add missing translations

---

yarn.lock

fix yarn lock

---

.github/workflows/init-release.yml

Reverts opencrvs/opencrvs-countryconfig#744

Revert "Creating draft release from workflow"

---

CHANGELOG.md
infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.staging-deploy.yml

fix (v.1.8.0): Add HEARTH_MONGO_URL to docker compose files.

---

src/form/v2/birth/index.ts

Resolves comment: https://github.com/opencrvs/opencrvs-core/issues/9385#issuecomment-2893308826

Display 'Place of birth' on summary even if details on incomplete declaration are missing

---

infrastructure/server-setup/tasks/users.yml

This PR is followup to recently merged: https://github.com/opencrvs/opencrvs-countryconfig/pull/755
users.yml was missed

fix: Change current_user to ansible_user

---

src/translations/client.csv

Adds the missing language item from the admin view

[OCRVS-9596] Add import to messages

---

CHANGELOG.md
src/form/birth/required-fields.ts
src/form/death/required-fields.ts

I will also do for all other location base field, I just need confirmation that this is a correct approach
https://github.com/opencrvs/opencrvs-core/issues/9311
Linked Core PR: https://github.com/opencrvs/opencrvs-core/pull/9602

Ensure placeOfBirth only shows active facilities

---

src/translations/client.csv

change copy to Search result*s*

chore: add plural

---

src/translations/client.csv

fix: add translations for draft

---

src/api/certificates/source/birth-certificate.svg
src/api/certificates/source/death-certificate.svg
src/api/certificates/source/marriage-certificate.svg

Fix for https://github.com/opencrvs/opencrvs-core/issues/9837
As countryconfig has no reference of qr code in certificates, the issue related to overlapping with qr code is submitted in farajaland 
https://github.com/opencrvs/opencrvs-farajaland/pull/1486

[OCRVS-9837] Fix certificate UI issues

---

src/translations/client.csv

Core PR: https://github.com/opencrvs/opencrvs-core/pull/9912

'Required for registration' to 'Required' as default required validation error message

---

CHANGELOG.md
infrastructure/backups/backup.sh
infrastructure/backups/restore.sh

We have deprecated OpenHIM a long time ago, but it seems to still be referred to many times
ISSUE : [#9732](https://github.com/opencrvs/opencrvs-core/issues/9732)

Remove OpenHIM mentions from backup scripts(ocrvs-9732)

---

CHANGELOG.md

Merge v1.7.3 into v1.8.0

---

src/api/workqueue/workqueueConfig.ts
src/data-seeding/roles/roles.ts

fix: Configuration of `Requires update` workqueue

---

src/translations/client.csv

chore: update review correction request messages

---

src/form/tennis-club-membership.ts
src/form/v2/birth/forms/correctionForm/index.ts
src/translations/client.csv

chore: add verify id translation for correction

---

src/translations/client.csv

Fix: Remove translation with ... as key

---

package.json
yarn.lock

Enable AJV caching

---

package.json
yarn.lock

chore: bump up toolkit

---

src/client-config.prod.js
src/form/v2/birth/forms/pages/child.ts
src/index.ts

Deploy v2 env

---

src/api/certificates/source/v2.birth-certificate-certified-copy.svg
src/api/certificates/source/v2.birth-certificate.svg
src/api/certificates/source/v2.death-certificate-certified-copy.svg
src/api/certificates/source/v2.death-certificate.svg
src/api/certificates/source/v2.tennis-club-membership-certificate.svg
src/api/certificates/source/v2.tennis-club-membership-certified-certificate.svg

[OCRVS-10098] Update name handlebars

---

src/index.ts

[OCRVS-10276] Migration-time reindexing for ES data

---

postman/Event Notification - v1.9.0.postman_collection.json

Core PR: https://github.com/opencrvs/opencrvs-core/pull/10329

Update postman for Notification API changes

---

src/translations/client.csv

Issue: https://github.com/opencrvs/opencrvs-core/issues/10097
core pr: https://github.com/opencrvs/opencrvs-core/pull/10348

Added missing translation

---

package.json
src/api/notification/email-templates/birth/rejection.html
src/api/notification/email-templates/index.ts
src/api/notification/handler.ts
src/api/notification/sms-service.ts
src/config/routes/userNotificationRoutes.ts
yarn.lock

fix: all user notification

---

package.json
yarn.lock

https://github.com/opencrvs/opencrvs-core/pull/10384

chore: update toolkit version

---

src/translations/client.csv

added translations for workbox runtime error modal

---

src/translations/client.csv

Adds translation key for Import/Exprot system client.
Core PR: https://github.com/opencrvs/opencrvs-core/pull/10416

Add Import/Export translation

---

infrastructure/clear-all-data.sh

Reverts opencrvs/opencrvs-countryconfig#1016

Revert "use postgres superuser credentials"

---

infrastructure/docker-compose.deploy.yml
infrastructure/redis/redis.conf

see description at https://github.com/opencrvs/opencrvs-core/pull/10503

fix: Switch to official redis image (#10173)

---

src/constants.ts
src/environment.ts
src/index.ts

Parse the V2_EVENTS environment variable properly using envalid, so that "boolean" value is used.

chore: parse V2_EVENTS via envalid

---

src/index.ts

add shortcircuit if no analytics env configured

---

src/form/v2/birth/forms/pages/child.ts

Update child address id fields

---

src/api/certificates/source/v2.death-certificate-certified-copy.svg
src/api/certificates/source/v2.death-certificate.svg
src/index.ts
yarn.lock

Resolves https://github.com/opencrvs/opencrvs-core/issues/10613
Some e2e tests: https://github.com/opencrvs/opencrvs-farajaland/pull/1723
Also minor logging improvement to countryconfig server

Fix bugs on death certificates

---

src/api/certificates/source/v2.birth-certificate-certified-copy.svg
src/api/certificates/source/v2.birth-certificate.svg
src/api/certificates/source/v2.death-certificate-certified-copy.svg
src/api/certificates/source/v2.death-certificate.svg

Resolves: https://github.com/opencrvs/opencrvs-core/issues/10550
See dicussion: https://opencrvsworkspace.slack.com/archives/C07NQAULENB/p1759488917005049
E2e test: https://github.com/opencrvs/opencrvs-farajaland/pull/1730

Fix certificates to use correct createdAtLocation

---

src/form/v2/death/advancedSearch.ts
src/form/v2/death/forms/pages/eventDetails.ts

Fixes: https://github.com/opencrvs/opencrvs-core/issues/10574

fix: death advanced search config
