opencrvs/opencrvs-countryconfig

infrastructure/monitoring/kibana/setup-config.sh

While debugging perf issues on deployment I noticed that we are using 9 year old `jq` images causing depreaction warnings like
```docker: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/stedolan/jq:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at [https://docs.docker.com/go/deprecated-image-specs/.](https://docs.docker.com/go/deprecated-image-specs/)```
Update to latest official ones from https://github.com/jqlang/jq?tab=readme-ov-file#docker-image

Update jq images to official ones to avoid deprecation breakage

---

CHANGELOG.md
src/form/marriage/index.ts
src/translations/client.csv

Updated the item names in the update modal for marriage declarations to:
- 'Informant' in place of 'Registration name'
- 'Bride' in place of 'Print and issue to bride'
- 'Groom' in place of 'Print and issue to Groom'
related core pull request: https://github.com/opencrvs/opencrvs-core/pull/7066

Fix Correct item names in update modal for marriage declaration

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
infrastructure/deployment/deploy.sh
infrastructure/environments/setup-environment.ts

Closes: https://github.com/opencrvs/opencrvs-core/issues/7018
- Allow only numbers in user input / setup-environment.ts
- Reasonable instructions given to use default port 22 unless user is advanced and configured to use some other port than 22
- Manually tested the yarn environment:init cli tool, it logged the right port (22 or 77 depending on input) to terminal, added it to .env.{env} and to a GitHub repo correctly

Update setup-environment.ts & deploy.sh to support non-default SSH port

---

.github/workflows/publish-to-dockerhub.yml
.trivyignore.yaml
trivy.yml

@rikukissa what do you think of adding Trivy scan to countryconfig?  Not sure I have configured the .trivyignore correctly
Example run: https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/9503686481/job/26194680803
Errors not thrown, but there's a lot of output:
TODO:

Trivvy scan

---

infrastructure/deployment/deploy.sh

In https://github.com/opencrvs/opencrvs-core/pull/6919 we add a new baseimage that is part of compose for convenience of builds. But during deploys we should always skip this

Ignore baseimage when deploying

---

src/form/addresses/address-fields.ts
src/form/addresses/index.ts
src/form/common/default-validation-conditionals.ts
src/form/common/messages.ts
src/form/types/types.ts
src/utils/address-utils.ts

Show matching label depending on father's primary address selection.
- Extend `conditionalCase` type, allow passing `Conditional[]`
I could not get to a nicely working solution without utilising the `Conditional` type. I opted for not trying to modify the `primaryAddress` `previewGroup` since it was much more involved.
Let me know what you think. ~~I left a todo comment which I intend to fix if you find the approach ok.~~

fix(ocrvs-5086): show different label when father address matches

---

docker-compose.yml
infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.development-deploy.yml
infrastructure/docker-compose.production-deploy.yml
infrastructure/docker-compose.qa-deploy.yml
infrastructure/docker-compose.staging-deploy.yml

PR to match the same removal in core, see more details at https://github.com/opencrvs/opencrvs-core/pull/7350

Remove deprecated version from compose files

---

src/api/notification/sms-service.ts

As text is a stream it can only be accessed once otherwise it would error.

fix: stop accessing response text multiple times

---

.github/workflows/auto-pr-to-release.yml

Same changes: https://github.com/opencrvs/opencrvs-core/pull/7397
Issue:
1. When the PR bot was successful, the first commit got removed due `cherry-pick` behaviour.  In `git cherry-pick h4shba..h4ashb` left side is exclusive. It differs from what `git log` shows with corresponding range syntax.
2. The commands provided by PR had the same behaviour. From a quick look there has not been many manual "Merge changes from PR" fixes that utilise the provided syntax. People tend to fix it by other means.
3. When referring to commit range, it can exists in multiple branches. Picking from `develop`
yields different result than the feature branch.
Changes:
1. Include first commit to cherry-pick range
2. Print out commits to PR body when automatic cherry-pick fails.
Sample PR: …

Include first commit to range, render commits to body

---

infrastructure/environments/github.ts

What had happened was by default Github APIs only return 30 first secrets / variables. 
This caused `SSH_KEY`, `SSH_USER` and other variables at the end of the variables list to always be asked from the user.

Fix environment creator asking user to resupply some Github variables and secrets on every run

---

.github/workflows/publish-release.yml
CHANGELOG.md

A few small fixes here:
- Fix tagging mechanism so it always uses the branch defined as the "Branch to build from"
- Add descriptive commit messages to merge commits created by the pipeline
- Use the "Release tag" input as the tag to be created instead of reading a version from package.json
- Remove `v___` prefix from tags to allow countries use whatever versioning scheme

fix(releasing): Explicitly specify from which branch the release tag should be created from OCRVS-7369

---

CHANGELOG.md
src/form/addresses/index.ts
src/form/birth/index.ts
src/form/death/index.ts
src/form/marriage/index.ts

Closes https://github.com/opencrvs/opencrvs-core/issues/7404

OCRVS-7404 Fix: Remove unnecessary dividers in the declaration forms

---

CHANGELOG.md
src/api/notification/email-service.ts
src/api/notification/handler.ts
src/api/notification/sms-service.ts
src/logger.ts
tsconfig.json

https://github.com/opencrvs/opencrvs-core/issues/7181

Redact sensitive user information from log

---

infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.staging-deploy.yml

We started deploying Storybook to Cloudflare Pages ( opencrvs.pages.dev ) so we don't need to include it in deployments anymore.

chore: remove storybook from deployment

---

CHANGELOG.md
infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.development-deploy.yml
infrastructure/docker-compose.qa-deploy.yml
infrastructure/environments/setup-environment.ts

The country value is defaulted to FAR in core, but it changes per every environment so it shouldn't be defaulted in production. The environment validation caught this issue. Updated to ask for it in the setup environment script.

feat: ask for COUNTRY in setup environment

---

CHANGELOG.md
src/translations/client.csv

A request came for the clients to change the labels for "First name(s)" to "User's first name". Also change "Last name" to "User's surname" for clarity and less confussion.
https://github.com/opencrvs/opencrvs-core/issues/6830

feat: Update system user form fields translations

---

infrastructure/server-setup/inventory/development.yml

This reverts commit b491a991bed13241733500d979b9b0e3f55ecfd6.

Revert "chore: amend development.yml for deployment (#299)"

---

CHANGELOG.md
src/translations/client.csv

This is to allow country implementation to have custom Full name ordering e.g start with LastName or FirstName
https://github.com/opencrvs/opencrvs-core/issues/6830

feat: Add humanName constant to the copy

---

CHANGELOG.md
infrastructure/deployment/deploy.sh
infrastructure/server-setup/tasks/docker.yml

The docker images clean up is set to deploy script 
rather than from cron
Issue:
https://github.com/opencrvs/opencrvs-core/issues/7896

Clean images on deploy

---

CHANGELOG.md
infrastructure/docker-compose.deploy.yml
infrastructure/server-setup/tasks/swap.yml

Minor improvements for things I found while testing 1.6.0 infrastructure.
While I was testing 1.6.0, I noticed my staging environment not working. When trying to reset and seed the environment, I noticed reset not working as there was no replica set initialised in MongoDB. What had happened was this service failing for whatever reason. Kicking it back up and then doing a reset fixed the issue.

Always retry mongo-on-update on failure

---

infrastructure/server-setup/inventory/backup.yml
infrastructure/server-setup/inventory/production.yml
infrastructure/server-setup/inventory/qa.yml
infrastructure/server-setup/inventory/staging.yml

This reverts commit b7581efe9e195bc786fd73e54eec1b3eaf270397, reversing changes made to 1d3e670c3899b91e22df460b7eee713363258ac1.

Revert "Merge pull request #324 from opencrvs/server-config"

---

CHANGELOG.md
src/form/types/types.ts

InitialValue can be used with the expression property in core to dynamically set the value based on other fields.
This PR syncs the types with the country config to make that functionality clear.

chore(v1.6.1): Add initial value type to match types in core

---

src/api/custom-event/handler.ts

The catch-all route can receive either legacy-FHIR or current Events v2. Therefore I've removed the parsing for now, as the individual routes such as `onRegisterHandler` do know which type of events they receive.

fix: on any action throwing on FHIR events

---

.github/workflows/close-stale-prs-after-30-days.yml

This workflow will add a label Stale to a PR (if the PR remains inactive for 20 days)
After 10 days of labeling a PR to stale it will close the PR.
and send some messages to the author.
**The main purpose of the workflow is Closing a PR which is inactive for 30 days**

OCRVS-8300 Workflow added which will close PR after 30 days of inactivity

---

package.json
src/form/tennis-club-membership.ts
src/form/v2/birth/__snapshots__/birth.test.ts.snap
src/form/v2/birth/forms/child.ts
src/form/v2/birth/forms/declare.ts
src/form/v2/birth/forms/informant.ts
src/form/v2/birth/index.ts
src/form/v2/person/address.ts
src/form/v2/person/index.ts
yarn.lock

- update toolkit
- update zod (toolkit uses `zod.string().date()` which was not available on the older version

chore: update fields to match toolkit changes

---

src/translations/client.csv

If the translation is a completely null string, core throws an error as it thinks it's missing.

fix: form.field.label.empty not being reckognized by core

---

CHANGELOG.md
infrastructure/server-setup/files/sshd_audit_hardening.22.04.conf
infrastructure/server-setup/files/sshd_audit_hardening.24.04.conf
infrastructure/server-setup/tasks/users.yml

This PR aims to fix issue described at https://github.com/opencrvs/opencrvs-core/issues/7542 by using scripted documentation from https://www.ssh-audit.com/hardening_guides.html#ubuntu_24_04_lts
- Added files folder to keep files for upload by ansible
- Test results when /etc/ssh/moduli doesn't have short DH keys:
- Ubuntu 22.04: https://github.com/adskyiproger/opencrvs-countryconfig/actions/runs/13326572681/job/37221022719
- Ubuntu 24.04: https://github.com/adskyiproger/opencrvs-countryconfig/actions/runs/13327065548/job/37222596865
- Test results when /etc/ssh/moduli has short DH keys:
- Ubuntu 22.04: https://github.com/adskyiproger/opencrvs-countryconfig/actions/runs/13326711225/job/37221458269
- Ubuntu 24.04: https://github.com/adskyiproger/opencrvs-countryconfig/actions/runs/133283441 …

fix: Insecure SSH configuration #7542

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
.github/workflows/seed-data.yml
.github/workflows/test.yml
CHANGELOG.md

Added fixed node version from .nvmrc to avoid inconsistency node version defined in yarn.lock and default runners node version.
Tests:
- https://github.com/adskyiproger/opencrvs-countryconfig/actions/runs/13385308826/job/37380824026
- `Compile, lint and test / test` are executed within PR

Added fixed node version

---

src/api/dashboards/queries.ts

The generated documents were being merged into the corrections collection on `_id` field but as they were not being projected from the parent document, a new one was generated for each which defeated the purpose of them being used as the basis for merging.

fix: project _id from Task to corrections

---

.github/workflows/deploy-prod.yml

Manual approval process is the flow that should be implemented for us in opencrvs-farajaland fork or configuration for particular country, but not for repository exposed as part of the product.
E/g Someone makes a fork from opencrvs countryconfig and faces an issue with github action waiting for approval from our core team, like here: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/13457268501/job/37603920565

fix: Remove manual approval for staging and production deployment

---

.github/workflows/on-pull-request.yaml

1. Sync to Farajaland without conflicts: https://github.com/opencrvs/poc-core-test/actions/runs/13568515297, slack message: 
2. Sync to Farajaland failed due to conflict and PR doesn't exist: https://github.com/opencrvs/poc-core-test/actions/runs/13569504713/job/37930609422, slack message:
3. Sync to Farajaland failed due to conflict and PR exists: https://github.com/opencrvs/poc-core-test/actions/runs/13568453465/job/37927002873, Slack message: 
4. Case with failure was not fully tested, but should work properly as well.
All slack messages can be found here: https://opencrvsworkspace.slack.com/archives/C02LU432JGK/p1740665493604159
**NOTE:** THIS CODE was test on dedicated repositories, probably followup PR or creating dedicated secret for `gh` will be required:
- …

feat: Auto sync changes to Farajaland from countryconfig (#8716)

---

.github/workflows/on-pull-request.yaml

This PR is follow up to https://github.com/opencrvs/opencrvs-countryconfig/pull/450
`gh` doesn't allow properly create PR between fork and upstream repositories within the same organisation.
- Notifications are not send on success sync with Farajaland.
- Previously PR was created from upstream/branch to farajaland/branch. Now workflow creates sync-branch in Farajaland from upstream/branch. PR is created from farajaland/sync-branch to farajaland/branch
- Moved slack channel hardcode to variables
- Success sync without conflicts: https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/13626229499/job/38083968779
- Conflicts detected: https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/13626550275/job/38084902989
Link to slack messages: …

fix: Create PR in Farajaland repository

---

CHANGELOG.md
src/form/birth/index.ts
src/form/death/index.ts
src/form/marriage/index.ts
src/form/types/validators.ts
src/translations/client.csv

Add the isAgeInYearsBetween and deprecate the isInformantOfLegalAge validator To warn countries still using it that it will not be supported in future releases
linked Core PR: https://github.com/opencrvs/opencrvs-core/pull/8430
https://github.com/opencrvs/opencrvs-core/issues/7636

fix: Add the isAgeInYearsBetween validator

---

.github/workflows/get-secret-from-environment.yml

This PR provides fix for https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Related issue is: https://github.com/opencrvs/opencrvs-core/issues/8798
More information how to keep variables backward compatible are here: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter
General rule is:
Replace 
```
echo "::set-output name=<key>::<value>"
```
With
```yaml
echo "<key>=<value>" >> $GITHUB_OUTPUT
```
Access results by the same way:
```
echo ${{ steps.<action step>.outputs.<key> }}
```

fix: Deprecating save-state and set-output commands (#8798)

---

.github/workflows/on-pull-request.yaml

Goal of this PR is to improve handling conflicts in automatic PRs.
Automatic sync from countryconfig to Farajaland has 2 flows:
- No conflicts between develop branches
- Farajaland branch has conflicts and merge from countryconfig is not possible
First path was well tested within last 2 weeks, second pass was not properly handled. PRs were created, but branch conflicts were ignored: https://github.com/opencrvs/opencrvs-farajaland/pull/1283/files <img width="1442" alt="image" src="https://github.com/user-attachments/assets/b4b4b03d-9dce-40b3-8340-ea5e09c7e301" />
This PR fixes behavior for second path, example run: https://github.com/opencrvs/opencrvs-farajaland/pull/1285

Fix sync changes from countryconfig to Farajaland

---

.github/workflows/publish-to-dockerhub.yml
build-and-push.sh
package.json
yarn.lock

This PR is a small piece of bigger changes: https://github.com/opencrvs/infrastructure
Soon we are going to introduce kubernetes support for OpenCRVS local development environment and cluster.
As part of introduces feature developers should be able to run opencrvs countryconfig without opencrvs core and vice versa. To be able to run it we need give developers stable image tag build from development branch, people will always know what to put in image tags.
Pipeline: https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/13990690689
The only active branch for opencrvs-countryconfig project is `develop`
https://hub.docker.com/repository/docker/opencrvs/ocrvs-countryconfig/tags?name=develop-tmp

fix: Add branch name tag

---

infrastructure/clear-all-data.sh

Goal of this PR is to fix error:
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [ocrvs] matches an alias, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [ocrvs] matches an alias, specify the corresponding concrete indices instead."},"status":400}{"results":[{"statement_id":0}]}
```
https://github.com/opencrvs/opencrvs-farajaland/blob/0258a786ba5d21690aeeda590104f1a80eee4d5b/infrastructure/clear-all-data.sh#L89-L90
Test results: https://github.com/adskyiproger/opencrvs-vadymland/actions/runs/14086430997/job/39451617192

fix: Delete all indices on elasticsearch

---

.github/workflows/block-pr-develop-to-release.yml

Introduced PR merge rules:
- Block PR merge from develop branch into release branch
Test PR from develop branch into release branch done at: https://github.com/opencrvs/opencrvs-countryconfig/pull/595
This PR will re-apply changes

fix: Adding blocking rules for PRs

---

src/form/v2/birth/forms/pages/father.ts

Birth form, fathers details fixes:
- Set "Yes" as default value for "same as mothers usual place of residence"
- Hide address fields unless value is "No"

Birth form, fathers details fixes

---

src/api/certificates/source/v2.tennis-club-membership-certificate.svg
src/form/v2/birth/forms/print-certificate.ts
src/translations/client.csv

Changes: 
- Update translation id
- Remove print in advance option until it's implemented
- Allow MOTHER/FATHER selection
- Update tennis club certificate

chore: add translation and template fixes

---

Tiltfile

This PR contains following fixes:
- Added README.md from infrastructure repository
- Fix: If infrastructure directory doesn't exist clone repository before including Tiltfile.common

fix: Added readme to resources menu;

---

src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts

Informant National ID was missing validation.
Also add validation to mother/father nid to make sure its not same as informant.

add validation to informant nid

---

infrastructure/server-setup/swarm.yml

This was a bug we discovered while doing other development of our pipelines. The issue is
1. Provision a cluster with 2 nodes
2. Run ansible provisioning again
3. Notice there's an error now as the swarm node already belongs to the swarm
**Expectation**
Joining the worker is skipped silently as it doesn't need to be done. Only when the node is a part of **some other** swarm, the error would need to be thrown
**Actual**
The logic incorrectly interprets the situation as an error and throws an exception. 
Clean slate provision of manager + worker: :white_check_mark: 
Rerun without code changes: :collision: 
Rerun with code changes: :white_check_mark: 
Rerun with worker attached to a swarm of its own: :collision:
Removed the worker from its own swarm and rerun: :white_check_mark:

Verify a worker to be added to docker swarm is not part of some other swarm

---

src/form/v2/birth/forms/pages/informant.ts

https://github.com/opencrvs/opencrvs-core/issues/9159#issuecomment-2812733350
Hide informant exact date of birth checkbox from review.

hide informant exact date of birth unknown

---

.github/workflows/test.yml

We are using yarn package manager, npm cache is empty:
Cache remains empty after `yarn install`:

fix: Cache service responded with 422

---

CHANGELOG.md
infrastructure/server-setup/tasks/users.yml

If environment was provisioned from version v1.8.0+ and later re-provisioned with older versions v1.7.0+, the provision script fails on ssh config update step due to syntax error in sshd_config.
"Match all" section should be present after "Match User..." in sshd_config
Configuration file snippet:
```
Match User provision
PasswordAuthentication no
AuthenticationMethods publickey
Match all
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key
```
Without `Match all` section sshd will fail to start with syntax error, example from provision script:
```
TASK [Check SSH config syntax] *************************************************
fatal: [farajaland-qa]: FAILED! => {"changed": true, "cmd": ["sshd", "-T"], "delta": "0:00:00.014118", "end": "2025-04-23 11:47:02.563045", …
```

fix: "Match all" section should be present after "Match User..."

---

CHANGELOG.md
infrastructure/docker-compose.deploy.yml
infrastructure/docker-compose.staging-deploy.yml

Redoing the pull request as per the new hotfix flows.
Allows connecting the config service directly to Mongo for location queries.
Related issue: https://github.com/opencrvs/opencrvs-core/issues/8665 and https://github.com/opencrvs/opencrvs-core/issues/9255

fix (v.1.6.4): Add HEARTH_MONGO_URL to docker compose files.

---

infrastructure/docker-compose.deploy.yml
infrastructure/rotate-secrets.sh

This PR aims to address issue https://github.com/opencrvs/opencrvs-farajaland/actions/runs/14771582556/job/41472399233
docker-compose on e2e environment has 2 placeholders "{{STACK}}.{{ts}}" on farajaland we have only one placeholder "{{ts}}"

fix: Drop STACK placeholder from docker-compose

---

.github/workflows/init-release.yml

Introducing a new workflow which will trigger a pipeline with a given version number like `1.6.4`  and have branches, PRs and a draft release created automatically

Release automation: automation pipeline for bootstrapping a new release(ocrvs-9396)

---

src/form/v2/birth/forms/pages/child.ts
src/form/v2/birth/index.ts

https://github.com/opencrvs/opencrvs-core/issues/9385
Ensure conditionals permit single birth location at once.
Test for e2e in another pr against farajaland

fix: show message on empty, show only one message for child location

---

src/api/certificates/source/v2.birth-certificate-certified-copy.svg
src/api/certificates/source/v2.birth-certificate.svg
src/form/v2/birth/index.ts

- Show registrar instead of creator as the registrar.
- Update helpers based on core changes
- Apply linting to svgs
matching core pr:
https://github.com/opencrvs/opencrvs-core/pull/9543
Samples:

fix: show the registrar instead of creator in certificate

---

src/api/certificates/source/v2.birth-certificate-certified-copy.svg
src/translations/client.csv

Resolves https://github.com/opencrvs/opencrvs-core/issues/9556
* If informant type is mother or father, display their name in the certified copy as informant name
* If informant type is 'Someone else', display the inputted relation on the certified copy
* Add missing translation

display fathers and mothers name as informant, display inputted relation when relation is 'Someone else'

---

.github/workflows/test.yml
build-and-push.sh
infrastructure/mongodb/on-deploy.sh
start-prod.sh

`wait` command is widely used within OpenCRVS project to track service startup.
For mongo-on-update container `wait` command is installed at container startup, but never executed, log example from existing container on e2e environment:
```
....
#######
#######
Get:18 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
--
Setting up curl (7.68.0-1ubuntu2.25) ...
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
Processing triggers for libc-bin (2.31-0ubuntu9.15) ...
Reading package lists...
W: GPG error: http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 InRelease: The following signatures were invalid: EXPKEYSIG 656408E390CFB1F5 MongoDB 4.4 Release Signing Key <packaging@mongodb.com>
% Total    % Received % Xferd …
```

fix: Added wait command

---

start-prod.sh

Example of failed pipeline: https://github.com/opencrvs/opencrvs-countryconfig/commit/cbd7a9957eb013bebf027813ae2895a4a6239ff7
Root cause:
Node based images are using "/bin/sh" as shabang
`/bin/bash` doesn't exist, as a result container countryconfig doesn't start and fails with error:
```
/usr/src/app # ./start-prod.sh 
sh: ./start-prod.sh: not found
```
To fix the issue we need to drop shabang string or redifine with correct shell:
```
#!/bin/sh
```
```
/usr/src/app # ./start-prod.sh 
yarn run v1.22.22
$ ts-node --transpile-only -r tsconfig-paths/register src/index.ts
...
```

fix: Node based images are using "/bin/sh" as shabang

---

.github/workflows/clear-environment.yml
.github/workflows/deploy.yml

`actions/checkout@v4` checks out the code in a detached HEAD state and uses a shallow clone by default, which means:
- Git does not track branches in the usual way (HEAD isn't on main, release/..., etc.).
- Only a limited portion of the history is fetched (usually just the last commit).
- Commits made and pushed in one job do not persist to another job unless explicitly handled.
- Always use fetch-depth: 0 if you're manipulating history or pushing.
- Use ref: ${{ github.ref_name }} to ensure you're working on the actual branch.
Proof example: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/15258087389/job/42910430821
`farajaland-tmp1` was successfully created on Hetzner:
[create-server / Create New HCloud Environment](https://github.com/opencrvs/opencrvs-farajaland/actions/run …

fix: Add checkout depth to fix default behaviour of github action

---

package.json
src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts
src/form/v2/birth/index.ts
src/form/v2/person/index.ts
yarn.lock

This pull request removes indirection from the form configuration:
```ts
id: `${PersonType.father}.detailsNotAvailable`
``` 
are simplified to `id: 'father.detailsNotAvailable'` to make searching for fields easier.
```ts
dateOfEvent: field('child.dob').getId(),
```
can now be used just as 
```ts
dateOfEvent: field('child.dob'),
```
This should be the canonical way of referring to a field and serialise to `{$$field: 'child.dob'}`

Country config syntax tweaks

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
.github/workflows/seed-data.yml

This hot-fix aims to give a better way to configure node version between releases. See releated slack convo: https://opencrvsworkspace.slack.com/archives/C07M2FETFFB/p1749801415129169

fix: Change the way of defining node version and replace cd commands with working-directory

---

.github/workflows/on-pull-request.yaml

If a step fails, then the slack ping is never send about the error.
Add flag for the action to perform next ones

fix: continue on error to send message about it in slack

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
CHANGELOG.md

Related issue: https://github.com/opencrvs/opencrvs-core/issues/6984
Country config field is optional now:
- If not provided then last commit is used from country-config branch
- If provided then country-config will use provided commit
Edge cases:
- Country config doesn't have image build from last commit hash.
Input properties:
Skip checkout step:
Build summary:
Input properties:
Checkout for both repositories executed:
Build summary:

fix: Clarify the country config version a country is deployment

---

src/api/certificates/source/v2.death-certificate-certified-copy.svg
src/api/certificates/source/v2.death-certificate.svg
src/form/v2/death/advancedSearch.ts
src/form/v2/death/forms/declaration.ts
src/form/v2/death/forms/pages/deceased.ts
src/form/v2/death/forms/pages/documents.ts
src/form/v2/death/forms/pages/informant.ts
src/form/v2/death/forms/pages/spouse.ts
src/form/v2/death/forms/printForm/collector-identity-verify.ts
src/form/v2/death/forms/printForm/collector-other.ts
src/form/v2/death/forms/printForm/collectors.ts
src/form/v2/death/index.ts

Use `Name` field for person names instead of `Text` fields. This makes full name searches possible.
Fix bugs found in the `Upload supporting documents` page in the death v2 form

Use NAME field in V2 death forms and supporting documents fixes

---

infrastructure/docker-compose.deploy.yml

wrong lines of code was introduced while merge release branch into develop: https://github.com/opencrvs/opencrvs-countryconfig/commit/daab07d9ff4f73f5147f823c186f79844abf1b33#diff-ba8e76e28deb79c9af80270674a0f04af642ba68d7b1c608ed5790db9cc6f4c8
OpenCRVS v1.8.1 doesn't have authorisation enabled for redis (or Valkey)
See latest changelog at https://github.com/opencrvs/opencrvs-core/blob/develop/CHANGELOG.md
Redis ACLs are well tested and working in latest code on Farajaland fork: https://github.com/opencrvs/opencrvs-farajaland/commit/6d131430ba97e374159f249019f1130780c99a94

fix: Change Valkey to Redis

---

infrastructure/backups/restore.sh
infrastructure/clear-all-data.sh
infrastructure/docker-compose.deploy.yml

1. Specify minor version to avoid changes in env.
Issue:
- Deployment was succesful. First clear errors happened during environment reset.
- Reset process halted and left the environment in half-finished (broken) state.
Cause:
- We use postgres image: postgres:17
- Image source was updated some days ago by postgres team
- image update changed base image and underlying OS dependency (collation) version was updated.
- postgres depends on it for indexing. System threw an error when version mismatch was detected.
- Clearing script drops events database but default databases (postgres, template1) remain.

chore: specify postgres minor version to stabilise envs

---

src/form/v2/birth/forms/pages/father.ts

Fix of https://github.com/opencrvs/opencrvs-core/issues/10293#issuecomment-3236485893
`parent: field('mother.detailsNotAvailable)` when a parent field is updated, the value of the field itself gets reset. So when we click the CHECKBOX of the `mother.detailsAvailable`, `father.addressSameAs` is reset and set to defaultValue which is `Yes` and its original address gets hidden. 
**Solution**: We change the `dafaultValue` of the field `father.addressSameAs` so that original address is not reset.

chore: update default value of father address field

---

.github/workflows/publish-to-dockerhub.yml

This PR aims to address the issue for multi-arch manifests created with `docker manifest create`: https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/17555349167/job/49858711010
✅ https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/17556014643
✅ https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/17556134832
✅ https://github.com/opencrvs/opencrvs-countryconfig/actions/runs/17556017848
> NOTE: there is no need to update changelog

fix: docker.io/***/***:c28a386 is a manifest list

---

src/form/v2/birth/dedupConfig.ts

Extend dedupConfig to match mother by NID, passport, or BRN

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml

Warning example: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/17670049818/job/50219598603
**What changed:**
- Replaced complex bash loop with heredocs and multiple `jq` calls with a single, efficient `jq` command
- Combined secrets and variables processing into one operation
- Maintained the same filtering logic (excludes values containing newlines like SSH keys)
**Benefits:**
- **Cleaner code**: Reduced ~30 lines to ~8 lines
- **Better performance**: Single `jq` execution instead of multiple processes
- **Improved readability**: Eliminated complex bash loops and heredoc syntax
- **Same functionality**: Preserves newline filtering and output format
**Technical details:**
- Uses `jq -n` (null input) with GitHub Actions' `toJSON()` functions
- Merges secrets and vars objects …

fix: Here-doc warning for new lines

---

infrastructure/environments/setup-environment.ts

Related github issue: https://github.com/opencrvs/opencrvs-core/issues/10426
This PR adds postgress admin secrets to github environment secrets
> NOTE: This PR doesn't modify logic of ENCRYPTION_KEY & BACKUP_ENCRYPTION_PASSPHRASE life-cycle since they are already read-only. There is no way to update listed secrets by `yarn ...`
Testing was performed under Farajaland repository
New dummy environment was created: `dev1`
`yarn environment:init` was pointed to `dev1` on `Other` selection:
Screenshots from environment creation stage:
Post creation screenshots:
Values created by environments:init script:
postgres container values:
Provision: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/17731354214
Deployment: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/1773228242 …

fix: yarn environment:init should create Postgres secrets

---

src/data-seeding/roles/roles.ts

Remove read option from low level users by default. They can still read the ones created by them

fix: prevent low-level users from reading any event

---

package.json

The previous script required you to install `psql`, which is not necessary due to Docker already having it. Lets run the `psql` commands inside the Postgres container to fix having to install PostgreSQL locally.

run postgres in Docker instead of locally

---

src/form/v2/death/forms/pages/deceased.ts
src/form/v2/death/forms/pages/eventDetails.ts
src/form/v2/death/forms/pages/informant.ts

Resolves: https://github.com/opencrvs/opencrvs-core/issues/10221
Define certain death form PII fields as `secured: true`

Use secured fields in death form

---

package.json
src/api/notification/informantNotification.ts
src/form/tennis-club-membership.ts

chore: add new field

---

src/form/v2/death/forms/pages/deceased.ts
src/form/v2/death/forms/pages/eventDetails.ts
src/translations/client.csv

Resolves: https://github.com/opencrvs/opencrvs-core/issues/10527
E2e tests: https://github.com/opencrvs/opencrvs-farajaland/pull/1728

Add validations to death form deceased birth date and event date

---

src/form/v2/death/forms/pages/eventDetails.ts
src/translations/client.csv

fix(death-form-field): amend reason for late registration field label

---

src/api/certificates/handler.ts
src/api/certificates/source/v2.birth-certificate-certified-copy.svg
src/api/certificates/source/v2.death-certificate-certified-copy.svg

issue: https://github.com/opencrvs/opencrvs-core/issues/10584
core pr: https://github.com/opencrvs/opencrvs-core/pull/10599

Update birth certificate SVG to use streetLevelDetails fields and correct informant relation handling

---

package.json
src/form/tennis-club-membership.ts
src/form/v2/birth/forms/pages/child.ts
src/form/v2/birth/forms/pages/father.ts
src/form/v2/birth/forms/pages/informant.ts
src/form/v2/birth/forms/pages/mother.ts
src/form/v2/birth/forms/printForm/collector-other.ts
src/form/v2/birth/forms/printForm/index.ts
src/form/v2/death/forms/pages/eventDetails.ts
src/form/v2/death/forms/pages/informant.ts
src/form/v2/death/forms/pages/spouse.ts
src/form/v2/death/forms/printForm/collector-other.ts
yarn.lock

Change fields not to use `_` in id.
